### ISSUE TITLE
Modbus Error - Returned Base Register does not match that from request

### ISSUE THREAD

**Issue by rjenx** [cdpuk/givenergy-local#18]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug

Not sure if this is a problem but I have multiple errors appearing in my logs some (like this one) has hundreds of occurrences. 
```
This error originated from a custom integration.

Logger: givenergy_modbus
Source: custom_components/givenergy_local/coordinator.py:69
Integration: GivEnergy Local (documentation, issues)
First occurred: 29 December 2022 at 15:25:04 (758 occurrences)
Last logged: 14:55:15

Returned base register (0) does not match that from request (60).
Returned base register (0) does not match that from request (180).
Transaction failed
Did not receive expected response type: ReadInputRegistersResponse != ModbusIOException
Did not receive expected response type: ReadInputRegistersResponse != ErrorResponse
```

## Debug log

```text

Add your logs here.

```

**Comment by cdpuk** [comment]
Hi, it's not a problem with the integration, but people do see this fairly frequently. Main things to check:
* Make sure your connection to the inverter is good (i.e. good Wi-Fi signal)
* Make sure you're not trying to read data using another tool (e.g. GivTCP or a second instance of the integration)

Even after that, I still might get a few of these per hour. With the current update speed of 30 seconds, a missed update shouldn't cause too big a gap in data. Your 758 occurrences sounds high, but I don't know what period of time that's over.

The real root cause is probably somewhere between the library used by this integration, and GivEnergy's modbus implementation.
