### ISSUE TITLE
Possibly a cosmetic issue - reporting "Today" on HA's main dashboard regardless of interval selected.

### ISSUE THREAD

**Issue by digdilem** [cdpuk/givenergy-local#59]
Minor cosmetic issue: HA's Energy Dashboard shows "Today" regardless of the period selected.  

I wrote a full issue report for HA here: https://github.com/home-assistant/frontend/issues/17185  explaining the problem, with screenshots.  

They've closed it,  saying the string is there because I'm adding "Today" in my integration. I don't think _I_ am, but rather than the Givenergy integration is adding this in its output. 

Obviously this is a very small issue, if it is indeed an issue with the integration. If you consider this not fixable, or not being generated by your integration, I will not be offended if you close this without action, but felt I should raise it. 

Thanks for your work in providing this - it's been working perfectly!

**Comment by cdpuk** [comment]
It's a minor annoyance but unfortunately it's just how HA works. Some sensors really do need the time period in their names e.g. "PV Energy Toady" vs "PV Energy Total" - otherwise we've got a name collision. 

These names can't be customised for only the energy dashboard but you can change the entity name for display everywhere, including the Energy Dashboard. Most other dashboard components also allow names to be customised.
