### ISSUE TITLE
Charging not stopping when going into Eco mode

### ISSUE THREAD

**Issue by hilburn** [cdpuk/givenergy-local#97]
## Hardware and versions

* Inverter model & generation: Hybrid Gen 3 5kW
* Inverter firmware version: D0.307-A0.307
* Battery firmware version: 3015
* Home Assistant integration version: v2.0.6

## Describe the bug

Recently due to a change in my control scheme I've changed the Timed Charging to target 100% and cancel out of it early with a boolean triggering the automation (state>true: turn on charging, state>false: turn on eco mode) rather than changing the Timed Charging target to = current charge which I used to do.

Last night I noticed that the charging went beyond the return to Eco mode (green is the window where the boolean is true)

![image](https://github.com/user-attachments/assets/92482b08-ae97-40b8-9e1a-3db76931c4b5)

This seems to be because the Activate Eco Mode doesn't reset AC charging to off, or disables the Battery Charge Slot 1 - so while it's still in the charge slot (2-5am) I set, it still charges the battery despite nominally being in Eco mode and runs from the grid until the end of slot.

![image](https://github.com/user-attachments/assets/8cdf427b-5609-4c34-8cf0-e4201ba1ca92)

I'm not sure what's more sensible at this point, either changing the controls.md to reflect the additional step to actually turn off Timed Charging Mode, or to change the Eco mode to turn AC charging off

## Debug log

```

This isn't the sort of issue that requires debug logs

```

**Comment by cdpuk** [comment]
The behaviour of the "Activate Eco Mode" service is by design to match the behaviour of the GivEnergy app/portal. It's completely valid to have Eco mode on or off at the same time as AC charging being on or off; it's only when you're within the AC charging timeslot does charging actually happen.

There does appear to be a copy & paste mistake in `controls.md`, which incorrectly states that AC charging can be turned off by activating Eco mode. I'll make an update to fix that. The only way to turn it off is via `switch.battery_ac_charging`.

**Comment by hilburn** [comment]
That's fair! I wasn't sure if it was intended behaviour given it went against the docs so fixing the docs is perfectly valid :)
